---
# tasks file for roles/frontend
- name: Run frontend service
  docker_container:
    name: front
    image: linh2409/tp-devops-front:latest
    pull: true
    recreate: true
    networks:
      - name: frontend
    state: started
    restart_policy: unless-stopped
  vars:
    ansible_python_interpreter: /usr/bin/python3
